[env:coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
lib_deps = m5stack/M5Unified
board_build.partitions = huge_app.csv
board_build.embed_files = data/dex.bin
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
